
name: Release cities-skylines.cn


on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      # - name: Publish NetCoreApp
      #   run: |
      #     dotnet clean ./HanJie.CSLCN.WebApp
      #     dotnet publish -c:Release ./HanJie.CSLCN.WebApp

      - name: Publish Angular Client App
        run: |
          cd ./HanJie.CSLCN.WebApp/ClientApp
          [System.IO.Directory]::CreateDirectory("node_modules")
          Copy-Item -Path D:\CSL-CN\HanJie.CSLCN.WebApp\ClientApp\node_modules\* -Destination .\node_modules\ -Force -Recurse
          ng build --prod

  
