
name: Release cities-skylines.cn


on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Clean Publish Directory
        run: |
          dotnet clean ./HanJie.CSLCN.WebApp
          dotnet publish -c:Release ./HanJie.CSLCN.WebApp

      - name: Publish Angular Client App
        run: |
          cd ./HanJie.CSLCN.WebApp/ClientApp
          npm install
          ng build --prod

  
